#!/bin/sh
set -euxo pipefail

FILE=/usr/lib/jvm/java-17-temurin/bin/java
if [ -f "$FILE" ]; then
    echo "$FILE exists. Using alternate java name to test."
    $FILE --version
else
    echo "$FILE does not exist. Using default java to test."
    java --version
fi

RETVAL=$?
if [ $RETVAL -eq 0 ] ; then
    echo "PASS: temurin-17-bin startup test"
else
    echo "FAIL: temurin-17-bin startup test"
fi